services:
  - type: web
    name: sefer-aktarim-bosaltma-kontrol
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
